AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Services:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/service
      Runtime: go1.x
      Tracing: Active
      Events:
        GetServices:
          Type: Api
          Properties:
            Path: /services
            Method: get
        GetService:
          Type: Api
          Properties:
            Path: /service/{id}
            Method: get
  Requests:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/request
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRequests:
          Type: Api
          Properties:
            Path: /requests
            Method: get
        GetRequest:
          Type: Api
          Properties:
            Path: /request/{id}
            Method: get
        PostRequest:
          Type: Api
          Properties:
            Path: /request
            Method: post
  Cities:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/cities
      Runtime: go1.x
      Tracing: Active
      Events:
        GetRequests:
          Type: Api
          Properties:
            Path: /cities
            Method: get
        GetRequest:
          Type: Api
          Properties:
            Path: /city/{id}
            Method: get

Outputs:
  URL:
    Description: URL for HTTPS Endpoint
    Value:
      Fn::Join:
        - ''
        - - https://
          - Ref: ServerlessRestApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/"
          - Ref: ServerlessRestApiProdStage
